version: "3"
services:
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/php-fpm.docker
      args:
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
    volumes:
      - ./:/var/www
    environment:
      - "PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d"
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/nginx.docker
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - mysql
      - php-fpm
    volumes:
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx
  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./.dockerconfig/mysql:/var/lib/mysql